org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.java.home=C\:\\Users\\lihuo\\.gradle\\jdks\\eclipse_adoptium-21-amd64-windows.2
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
